# Generated by Django 4.1.3 on 2022-11-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('url_name', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=7)),
                ('up_since', models.DateTimeField()),
                ('frequency', models.IntegerField()),
                ('frequency_Interval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
            ],
        ),
    ]
