# Generated by Django 4.1.3 on 2022-11-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Superuser_code', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='urls',
        ),
    ]
