# Generated by Django 4.1.3 on 2022-12-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Superuser_code', '0002_delete_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='urldata',
            options={'verbose_name': 'Url Data', 'verbose_name_plural': 'Urls Data'},
        ),
        migrations.AlterField(
            model_name='urldata',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Superuser_code.status'),
        ),
    ]
